language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - ./tasks.py populate -n 100
  - ./tasks.py exportProduct -d /tmp/data
  - ./tasks.py importProduct -d /tmp/data
