#!/usr/bin/env bash

# If not on a virtual environment
#deactivate
#mkvirtualenv leniko --python=/usr/bin/python3.6
#workon leniko

# Fetch new
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

git pull origin "${GIT_BRANCH}"
pip install -r requirements.txt

rm -rf static
./manage.py collectstatic
