#!/usr/bin/env bash

py3clean .
redis-cli FLUSHDB
rm -rf db.sqlite3
rm -rf media
rm -rf static
./manage.py makemigrations
./manage.py migrate --run-syncdb
./manage.py createsuperuser --username tedi --email hkanelhs@yahoo.gr
./manage.py collectstatic
./manage.py runserver
