# Generated by Django 3.1.4 on 2021-03-27 17:08

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('isPayed', models.BooleanField(default=False)),
                ('isDispatched', models.BooleanField(default=False)),
                ('isRefundAsked', models.BooleanField(default=False)),
                ('isRefunded', models.BooleanField(default=False)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('billing_zip', models.CharField(blank=True, max_length=5, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_zip', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(default=None, editable=False)),
                ('quantity', models.IntegerField(editable=False)),
                ('unit_price', models.FloatField(editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order')),
            ],
        ),
    ]
