# Generated by Django 3.1.4 on 2021-01-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210131_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
