# Generated by Django 3.1.4 on 2020-12-25 10:34

from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import products.internal.enum


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='color',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Black', 'Black'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Slate Gray', 'Slate Gray'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Ivory', 'Ivory'), ('Beige', 'Beige'), ('White', 'White'), ('Dark Red', 'Dark Red'), ('Saddle Brown', 'Saddle Brown'), ('Sienna', 'Sienna'), ('Dark Blue', 'Dark Blue'), ('Royal Blue', 'Royal Blue'), ('Light Sky Blue', 'Light Sky Blue'), ('Cadet Blue', 'Cadet Blue'), ('Turquoise', 'Turquoise'), ('Aquamarine', 'Aquamarine'), ('Light Cyan', 'Light Cyan'), ('Teal', 'Teal'), ('Light Sea Green', 'Light Sea Green'), ('Dark Sea Green', 'Dark Sea Green'), ('Dark Olive Green', 'Dark Olive Green'), ('Olive', 'Olive'), ('Dark Green', 'Dark Green'), ('Green', 'Green'), ('Forest Green', 'Forest Green'), ('Sea Green', 'Sea Green'), ('Emerald', 'Emerald'), ('Indigo', 'Indigo'), ('Purple', 'Purple'), ('Dark Violet', 'Dark Violet'), ('Dark Khaki', 'Dark Khaki'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Dark Orange', 'Dark Orange'), ('Orange Red', 'Orange Red'), ('Coral', 'Coral'), ('Light Salmon', 'Light Salmon'), ('Pink', 'Pink'), ('Fire Brick', 'Fire Brick'), ('Red', 'Red'), ('Salmon', 'Salmon'), ('Indian Red', 'Indian Red')], default=products.internal.enum.ColorEnum['N'], enum_class=products.internal.enum.ColorEnum, max_length=16),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='diameter_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='diameter_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='stone',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Agate', 'Agate'), ('Amazonite', 'Amazonite'), ('Amethyst', 'Amethyst'), ('Aquamarine', 'Aquamarine'), ('Calcite', 'Calcite'), ('Carnelian', 'Carnelian'), ('Cassiterite', 'Cassiterite'), ('Chalcedony', 'Chalcedony'), ('Chrysocolla', 'Chrysocolla'), ('Chrysocolla Chalcedony', 'Chrysocolla Chalcedony'), ('Coral', 'Coral'), ('Diamond', 'Diamond'), ('Dolomite', 'Dolomite'), ('Emerald', 'Emerald'), ('Hematite', 'Hematite'), ('Jasper', 'Jasper'), ('Kyanite', 'Kyanite'), ('Labradorite', 'Labradorite'), ('Lapis Lazuli', 'Lapis Lazuli'), ('Lazulite', 'Lazulite'), ('Magnesite', 'Magnesite'), ('Malachite', 'Malachite'), ('Moonstone', 'Moonstone'), ('Onyx', 'Onyx'), ('Opal', 'Opal'), ('Pearl', 'Pearl'), ('Quartz', 'Quartz'), ('Rhodonite', 'Rhodonite'), ('Rose Quartz', 'Rose Quartz'), ('Ruby', 'Ruby'), ('Smoky Quartz', 'Smoky Quartz'), ('Sodalite', 'Sodalite'), ("Tiger's Eye", "Tiger's Eye"), ('Topaz', 'Topaz'), ('Tourmaline', 'Tourmaline'), ('Turquoise', 'Turquoise'), ('Zircon', 'Zircon')], default=products.internal.enum.StoneEnum['N'], enum_class=products.internal.enum.StoneEnum, max_length=22),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='width_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='width_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='color',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Black', 'Black'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Slate Gray', 'Slate Gray'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Ivory', 'Ivory'), ('Beige', 'Beige'), ('White', 'White'), ('Dark Red', 'Dark Red'), ('Saddle Brown', 'Saddle Brown'), ('Sienna', 'Sienna'), ('Dark Blue', 'Dark Blue'), ('Royal Blue', 'Royal Blue'), ('Light Sky Blue', 'Light Sky Blue'), ('Cadet Blue', 'Cadet Blue'), ('Turquoise', 'Turquoise'), ('Aquamarine', 'Aquamarine'), ('Light Cyan', 'Light Cyan'), ('Teal', 'Teal'), ('Light Sea Green', 'Light Sea Green'), ('Dark Sea Green', 'Dark Sea Green'), ('Dark Olive Green', 'Dark Olive Green'), ('Olive', 'Olive'), ('Dark Green', 'Dark Green'), ('Green', 'Green'), ('Forest Green', 'Forest Green'), ('Sea Green', 'Sea Green'), ('Emerald', 'Emerald'), ('Indigo', 'Indigo'), ('Purple', 'Purple'), ('Dark Violet', 'Dark Violet'), ('Dark Khaki', 'Dark Khaki'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Dark Orange', 'Dark Orange'), ('Orange Red', 'Orange Red'), ('Coral', 'Coral'), ('Light Salmon', 'Light Salmon'), ('Pink', 'Pink'), ('Fire Brick', 'Fire Brick'), ('Red', 'Red'), ('Salmon', 'Salmon'), ('Indian Red', 'Indian Red')], default=products.internal.enum.ColorEnum['N'], enum_class=products.internal.enum.ColorEnum, max_length=16),
        ),
        migrations.AlterField(
            model_name='earring',
            name='heigth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='stone',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Agate', 'Agate'), ('Amazonite', 'Amazonite'), ('Amethyst', 'Amethyst'), ('Aquamarine', 'Aquamarine'), ('Calcite', 'Calcite'), ('Carnelian', 'Carnelian'), ('Cassiterite', 'Cassiterite'), ('Chalcedony', 'Chalcedony'), ('Chrysocolla', 'Chrysocolla'), ('Chrysocolla Chalcedony', 'Chrysocolla Chalcedony'), ('Coral', 'Coral'), ('Diamond', 'Diamond'), ('Dolomite', 'Dolomite'), ('Emerald', 'Emerald'), ('Hematite', 'Hematite'), ('Jasper', 'Jasper'), ('Kyanite', 'Kyanite'), ('Labradorite', 'Labradorite'), ('Lapis Lazuli', 'Lapis Lazuli'), ('Lazulite', 'Lazulite'), ('Magnesite', 'Magnesite'), ('Malachite', 'Malachite'), ('Moonstone', 'Moonstone'), ('Onyx', 'Onyx'), ('Opal', 'Opal'), ('Pearl', 'Pearl'), ('Quartz', 'Quartz'), ('Rhodonite', 'Rhodonite'), ('Rose Quartz', 'Rose Quartz'), ('Ruby', 'Ruby'), ('Smoky Quartz', 'Smoky Quartz'), ('Sodalite', 'Sodalite'), ("Tiger's Eye", "Tiger's Eye"), ('Topaz', 'Topaz'), ('Tourmaline', 'Tourmaline'), ('Turquoise', 'Turquoise'), ('Zircon', 'Zircon')], default=products.internal.enum.StoneEnum['N'], enum_class=products.internal.enum.StoneEnum, max_length=22),
        ),
        migrations.AlterField(
            model_name='earring',
            name='width_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='width_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewelrycolor',
            name='color',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Black', 'Black'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Slate Gray', 'Slate Gray'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Ivory', 'Ivory'), ('Beige', 'Beige'), ('White', 'White'), ('Dark Red', 'Dark Red'), ('Saddle Brown', 'Saddle Brown'), ('Sienna', 'Sienna'), ('Dark Blue', 'Dark Blue'), ('Royal Blue', 'Royal Blue'), ('Light Sky Blue', 'Light Sky Blue'), ('Cadet Blue', 'Cadet Blue'), ('Turquoise', 'Turquoise'), ('Aquamarine', 'Aquamarine'), ('Light Cyan', 'Light Cyan'), ('Teal', 'Teal'), ('Light Sea Green', 'Light Sea Green'), ('Dark Sea Green', 'Dark Sea Green'), ('Dark Olive Green', 'Dark Olive Green'), ('Olive', 'Olive'), ('Dark Green', 'Dark Green'), ('Green', 'Green'), ('Forest Green', 'Forest Green'), ('Sea Green', 'Sea Green'), ('Emerald', 'Emerald'), ('Indigo', 'Indigo'), ('Purple', 'Purple'), ('Dark Violet', 'Dark Violet'), ('Dark Khaki', 'Dark Khaki'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Dark Orange', 'Dark Orange'), ('Orange Red', 'Orange Red'), ('Coral', 'Coral'), ('Light Salmon', 'Light Salmon'), ('Pink', 'Pink'), ('Fire Brick', 'Fire Brick'), ('Red', 'Red'), ('Salmon', 'Salmon'), ('Indian Red', 'Indian Red')], default=products.internal.enum.ColorEnum['N'], enum_class=products.internal.enum.ColorEnum, max_length=16),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='color',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Black', 'Black'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Slate Gray', 'Slate Gray'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Ivory', 'Ivory'), ('Beige', 'Beige'), ('White', 'White'), ('Dark Red', 'Dark Red'), ('Saddle Brown', 'Saddle Brown'), ('Sienna', 'Sienna'), ('Dark Blue', 'Dark Blue'), ('Royal Blue', 'Royal Blue'), ('Light Sky Blue', 'Light Sky Blue'), ('Cadet Blue', 'Cadet Blue'), ('Turquoise', 'Turquoise'), ('Aquamarine', 'Aquamarine'), ('Light Cyan', 'Light Cyan'), ('Teal', 'Teal'), ('Light Sea Green', 'Light Sea Green'), ('Dark Sea Green', 'Dark Sea Green'), ('Dark Olive Green', 'Dark Olive Green'), ('Olive', 'Olive'), ('Dark Green', 'Dark Green'), ('Green', 'Green'), ('Forest Green', 'Forest Green'), ('Sea Green', 'Sea Green'), ('Emerald', 'Emerald'), ('Indigo', 'Indigo'), ('Purple', 'Purple'), ('Dark Violet', 'Dark Violet'), ('Dark Khaki', 'Dark Khaki'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Dark Orange', 'Dark Orange'), ('Orange Red', 'Orange Red'), ('Coral', 'Coral'), ('Light Salmon', 'Light Salmon'), ('Pink', 'Pink'), ('Fire Brick', 'Fire Brick'), ('Red', 'Red'), ('Salmon', 'Salmon'), ('Indian Red', 'Indian Red')], default=products.internal.enum.ColorEnum['N'], enum_class=products.internal.enum.ColorEnum, max_length=16),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='stone',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Agate', 'Agate'), ('Amazonite', 'Amazonite'), ('Amethyst', 'Amethyst'), ('Aquamarine', 'Aquamarine'), ('Calcite', 'Calcite'), ('Carnelian', 'Carnelian'), ('Cassiterite', 'Cassiterite'), ('Chalcedony', 'Chalcedony'), ('Chrysocolla', 'Chrysocolla'), ('Chrysocolla Chalcedony', 'Chrysocolla Chalcedony'), ('Coral', 'Coral'), ('Diamond', 'Diamond'), ('Dolomite', 'Dolomite'), ('Emerald', 'Emerald'), ('Hematite', 'Hematite'), ('Jasper', 'Jasper'), ('Kyanite', 'Kyanite'), ('Labradorite', 'Labradorite'), ('Lapis Lazuli', 'Lapis Lazuli'), ('Lazulite', 'Lazulite'), ('Magnesite', 'Magnesite'), ('Malachite', 'Malachite'), ('Moonstone', 'Moonstone'), ('Onyx', 'Onyx'), ('Opal', 'Opal'), ('Pearl', 'Pearl'), ('Quartz', 'Quartz'), ('Rhodonite', 'Rhodonite'), ('Rose Quartz', 'Rose Quartz'), ('Ruby', 'Ruby'), ('Smoky Quartz', 'Smoky Quartz'), ('Sodalite', 'Sodalite'), ("Tiger's Eye", "Tiger's Eye"), ('Topaz', 'Topaz'), ('Tourmaline', 'Tourmaline'), ('Turquoise', 'Turquoise'), ('Zircon', 'Zircon')], default=products.internal.enum.StoneEnum['N'], enum_class=products.internal.enum.StoneEnum, max_length=22),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='width_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='width_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='circumference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='color',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Black', 'Black'), ('Dark Slate Gray', 'Dark Slate Gray'), ('Slate Gray', 'Slate Gray'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Ivory', 'Ivory'), ('Beige', 'Beige'), ('White', 'White'), ('Dark Red', 'Dark Red'), ('Saddle Brown', 'Saddle Brown'), ('Sienna', 'Sienna'), ('Dark Blue', 'Dark Blue'), ('Royal Blue', 'Royal Blue'), ('Light Sky Blue', 'Light Sky Blue'), ('Cadet Blue', 'Cadet Blue'), ('Turquoise', 'Turquoise'), ('Aquamarine', 'Aquamarine'), ('Light Cyan', 'Light Cyan'), ('Teal', 'Teal'), ('Light Sea Green', 'Light Sea Green'), ('Dark Sea Green', 'Dark Sea Green'), ('Dark Olive Green', 'Dark Olive Green'), ('Olive', 'Olive'), ('Dark Green', 'Dark Green'), ('Green', 'Green'), ('Forest Green', 'Forest Green'), ('Sea Green', 'Sea Green'), ('Emerald', 'Emerald'), ('Indigo', 'Indigo'), ('Purple', 'Purple'), ('Dark Violet', 'Dark Violet'), ('Dark Khaki', 'Dark Khaki'), ('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Dark Orange', 'Dark Orange'), ('Orange Red', 'Orange Red'), ('Coral', 'Coral'), ('Light Salmon', 'Light Salmon'), ('Pink', 'Pink'), ('Fire Brick', 'Fire Brick'), ('Red', 'Red'), ('Salmon', 'Salmon'), ('Indian Red', 'Indian Red')], default=products.internal.enum.ColorEnum['N'], enum_class=products.internal.enum.ColorEnum, max_length=16),
        ),
        migrations.AlterField(
            model_name='ring',
            name='stone',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('None', 'None'), ('Agate', 'Agate'), ('Amazonite', 'Amazonite'), ('Amethyst', 'Amethyst'), ('Aquamarine', 'Aquamarine'), ('Calcite', 'Calcite'), ('Carnelian', 'Carnelian'), ('Cassiterite', 'Cassiterite'), ('Chalcedony', 'Chalcedony'), ('Chrysocolla', 'Chrysocolla'), ('Chrysocolla Chalcedony', 'Chrysocolla Chalcedony'), ('Coral', 'Coral'), ('Diamond', 'Diamond'), ('Dolomite', 'Dolomite'), ('Emerald', 'Emerald'), ('Hematite', 'Hematite'), ('Jasper', 'Jasper'), ('Kyanite', 'Kyanite'), ('Labradorite', 'Labradorite'), ('Lapis Lazuli', 'Lapis Lazuli'), ('Lazulite', 'Lazulite'), ('Magnesite', 'Magnesite'), ('Malachite', 'Malachite'), ('Moonstone', 'Moonstone'), ('Onyx', 'Onyx'), ('Opal', 'Opal'), ('Pearl', 'Pearl'), ('Quartz', 'Quartz'), ('Rhodonite', 'Rhodonite'), ('Rose Quartz', 'Rose Quartz'), ('Ruby', 'Ruby'), ('Smoky Quartz', 'Smoky Quartz'), ('Sodalite', 'Sodalite'), ("Tiger's Eye", "Tiger's Eye"), ('Topaz', 'Topaz'), ('Tourmaline', 'Tourmaline'), ('Turquoise', 'Turquoise'), ('Zircon', 'Zircon')], default=products.internal.enum.StoneEnum['N'], enum_class=products.internal.enum.StoneEnum, max_length=22),
        ),
        migrations.AlterField(
            model_name='ring',
            name='width_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='width_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
