# Generated by Django 3.1.4 on 2020-12-26 16:11

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201226_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryphoto',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='img/jewelryPhoto'),
        ),
    ]
