# Generated by Django 3.1.4 on 2020-12-29 20:04

from django.db import migrations, models
import products.internal.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201226_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryphoto',
            name='photo',
            field=models.ImageField(upload_to=products.internal.models.JewelryPhoto.uploadTo),
        ),
    ]
