# Generated by Django 3.1.4 on 2021-01-13 00:00

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import products.internal.enum


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210110_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracelet',
            old_name='color',
            new_name='pcolor',
        ),
        migrations.RenameField(
            model_name='earring',
            old_name='color',
            new_name='pcolor',
        ),
        migrations.RenameField(
            model_name='necklace',
            old_name='color',
            new_name='pcolor',
        ),
        migrations.RenameField(
            model_name='ring',
            old_name='color',
            new_name='pcolor',
        ),
        migrations.AddField(
            model_name='jewelry',
            name='scolor',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[("{'id': 0, 'name': 'None', 'value': '#ffffff'}", "{'id': 0, 'name': 'None', 'value': '#ffffff'}"), ("{'id': 1, 'name': 'Black', 'value': '#000000'}", "{'id': 1, 'name': 'Black', 'value': '#000000'}"), ("{'id': 2, 'name': 'Dark Slate Gray', 'value': '#2F4F4F'}", "{'id': 2, 'name': 'Dark Slate Gray', 'value': '#2F4F4F'}"), ("{'id': 3, 'name': 'Slate Gray', 'value': '#708090'}", "{'id': 3, 'name': 'Slate Gray', 'value': '#708090'}"), ("{'id': 4, 'name': 'Gray', 'value': '#808080'}", "{'id': 4, 'name': 'Gray', 'value': '#808080'}"), ("{'id': 5, 'name': 'Silver', 'value': '#C0C0C0'}", "{'id': 5, 'name': 'Silver', 'value': '#C0C0C0'}"), ("{'id': 6, 'name': 'Ivory', 'value': '#FFFFF0'}", "{'id': 6, 'name': 'Ivory', 'value': '#FFFFF0'}"), ("{'id': 7, 'name': 'Beige', 'value': '#F5F5DC'}", "{'id': 7, 'name': 'Beige', 'value': '#F5F5DC'}"), ("{'id': 8, 'name': 'White', 'value': '#FFFFFF'}", "{'id': 8, 'name': 'White', 'value': '#FFFFFF'}"), ("{'id': 9, 'name': 'Dark Red', 'value': '#A52A2A'}", "{'id': 9, 'name': 'Dark Red', 'value': '#A52A2A'}"), ("{'id': 10, 'name': 'Saddle Brown', 'value': '#8B4513'}", "{'id': 10, 'name': 'Saddle Brown', 'value': '#8B4513'}"), ("{'id': 11, 'name': 'Sienna', 'value': '#A0522D'}", "{'id': 11, 'name': 'Sienna', 'value': '#A0522D'}"), ("{'id': 12, 'name': 'Dark Blue', 'value': '#00008B'}", "{'id': 12, 'name': 'Dark Blue', 'value': '#00008B'}"), ("{'id': 13, 'name': 'Blue Royal', 'value': '#4169E1'}", "{'id': 13, 'name': 'Blue Royal', 'value': '#4169E1'}"), ("{'id': 14, 'name': 'Light Sky Blue', 'value': '#87CEFA'}", "{'id': 14, 'name': 'Light Sky Blue', 'value': '#87CEFA'}"), ("{'id': 15, 'name': 'Cadet Blue', 'value': '#5F9EA0'}", "{'id': 15, 'name': 'Cadet Blue', 'value': '#5F9EA0'}"), ("{'id': 16, 'name': 'Turquoise', 'value': '#40E0D0'}", "{'id': 16, 'name': 'Turquoise', 'value': '#40E0D0'}"), ("{'id': 17, 'name': 'Aquamarine', 'value': '#7FFFD4'}", "{'id': 17, 'name': 'Aquamarine', 'value': '#7FFFD4'}"), ("{'id': 18, 'name': 'Light Cyan', 'value': '#E0FFFF'}", "{'id': 18, 'name': 'Light Cyan', 'value': '#E0FFFF'}"), ("{'id': 19, 'name': 'Teal', 'value': '#008080'}", "{'id': 19, 'name': 'Teal', 'value': '#008080'}"), ("{'id': 20, 'name': 'Light Sea Green', 'value': '#20B2AA'}", "{'id': 20, 'name': 'Light Sea Green', 'value': '#20B2AA'}"), ("{'id': 21, 'name': 'Dark Sea Green', 'value': '#8FBC8B'}", "{'id': 21, 'name': 'Dark Sea Green', 'value': '#8FBC8B'}"), ("{'id': 22, 'name': 'Dark Olive Green', 'value': '#556B2F'}", "{'id': 22, 'name': 'Dark Olive Green', 'value': '#556B2F'}"), ("{'id': 23, 'name': 'Olive', 'value': '#808000'}", "{'id': 23, 'name': 'Olive', 'value': '#808000'}"), ("{'id': 24, 'name': 'Dark Green', 'value': '#006400'}", "{'id': 24, 'name': 'Dark Green', 'value': '#006400'}"), ("{'id': 25, 'name': 'Green', 'value': '#008000'}", "{'id': 25, 'name': 'Green', 'value': '#008000'}"), ("{'id': 26, 'name': 'Forest Green', 'value': '#228B22'}", "{'id': 26, 'name': 'Forest Green', 'value': '#228B22'}"), ("{'id': 27, 'name': 'Sea Green', 'value': '#2E8B57'}", "{'id': 27, 'name': 'Sea Green', 'value': '#2E8B57'}"), ("{'id': 28, 'name': 'Emerald', 'value': '#50C878'}", "{'id': 28, 'name': 'Emerald', 'value': '#50C878'}"), ("{'id': 29, 'name': 'Indigo', 'value': '#4B0082'}", "{'id': 29, 'name': 'Indigo', 'value': '#4B0082'}"), ("{'id': 30, 'name': 'Purple', 'value': '#800080'}", "{'id': 30, 'name': 'Purple', 'value': '#800080'}"), ("{'id': 31, 'name': 'Dark Violet', 'value': '#9400D3'}", "{'id': 31, 'name': 'Dark Violet', 'value': '#9400D3'}"), ("{'id': 32, 'name': 'Dark Khaki', 'value': '#BDB76B'}", "{'id': 32, 'name': 'Dark Khaki', 'value': '#BDB76B'}"), ("{'id': 33, 'name': 'Gold', 'value': '#FFD700'}", "{'id': 33, 'name': 'Gold', 'value': '#FFD700'}"), ("{'id': 34, 'name': 'Yellow', 'value': '#FFFF00'}", "{'id': 34, 'name': 'Yellow', 'value': '#FFFF00'}"), ("{'id': 35, 'name': 'Orange', 'value': '#FFA500'}", "{'id': 35, 'name': 'Orange', 'value': '#FFA500'}"), ("{'id': 36, 'name': 'Dark Orange', 'value': '#FF8C00'}", "{'id': 36, 'name': 'Dark Orange', 'value': '#FF8C00'}"), ("{'id': 37, 'name': 'Orange Red', 'value': '#FF4500'}", "{'id': 37, 'name': 'Orange Red', 'value': '#FF4500'}"), ("{'id': 38, 'name': 'Coral', 'value': '#FF7F50'}", "{'id': 38, 'name': 'Coral', 'value': '#FF7F50'}"), ("{'id': 39, 'name': 'Light Salmon', 'value': '#FFA07A'}", "{'id': 39, 'name': 'Light Salmon', 'value': '#FFA07A'}"), ("{'id': 40, 'name': 'Pink', 'value': '#FFC0CB'}", "{'id': 40, 'name': 'Pink', 'value': '#FFC0CB'}"), ("{'id': 41, 'name': 'Bordeaux', 'value': '#B22222'}", "{'id': 41, 'name': 'Bordeaux', 'value': '#B22222'}"), ("{'id': 42, 'name': 'Red', 'value': '#FF0000'}", "{'id': 42, 'name': 'Red', 'value': '#FF0000'}"), ("{'id': 43, 'name': 'Salmon', 'value': '#FA8072'}", "{'id': 43, 'name': 'Salmon', 'value': '#FA8072'}"), ("{'id': 44, 'name': 'Indian Red', 'value': '#CD5C5C'}", "{'id': 44, 'name': 'Indian Red', 'value': '#CD5C5C'}"), ("{'id': 45, 'name': 'Blue Raf', 'value': '#20639B'}", "{'id': 45, 'name': 'Blue Raf', 'value': '#20639B'}")], default=products.internal.enum.ColorEnum['N'], enum_class=products.internal.enum.ColorEnum, max_length=58),
        ),
        migrations.DeleteModel(
            name='JewelryColor',
        ),
    ]
