# Generated by Django 3.1.4 on 2021-03-06 15:30

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import products.internal.enum


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210113_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='material',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[("{'id': 'NO', 'name': 'None'}", "{'id': 'NO', 'name': 'None'}"), ("{'id': 'BR', 'name': 'Brass'}", "{'id': 'BR', 'name': 'Brass'}"), ("{'id': 'SI', 'name': 'Silver 925'}", "{'id': 'SI', 'name': 'Silver 925'}"), ("{'id': '14', 'name': 'Gold 14K'}", "{'id': '14', 'name': 'Gold 14K'}"), ("{'id': '25', 'name': 'Gold 25K'}", "{'id': '25', 'name': 'Gold 25K'}")], default=products.internal.enum.MaterialEnum['N'], enum_class=products.internal.enum.MaterialEnum, max_length=34),
        ),
    ]
